/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package fyi.gomes

import com.slack.api.Slack
import io.ktor.application.*
import io.ktor.http.*
import io.ktor.request.*
import io.ktor.response.*
import io.ktor.routing.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*

fun Application.configureRouting() {
    routing {
        get("/") { call.respondText("HEllotard!!!!") }
        get("/slack") {
            val token = "TOKEN"
            val slack = Slack.getInstance()
            val response =
                    slack.methods(token).chatPostMessage {
                        it.channel("#general").text("This is a slack bot")
                    }

            call.respondText("Response is: $response")
        }
    }
}

fun main() {
    embeddedServer(Netty, port = 8080, host = "0.0.0.0") { configureRouting() }.start(wait = true)
}
